---
# ランナーのインストール先
github_runner_dir_base: /opt/actions-runner

# GitHub Actions Runnerバージョン番号
# https://github.com/actions/runner/releases/
github_runner_version: "2.303.0"

# GitHubのパーソナルアクセストークン
github_access_token: ""

# Organizetion用かどうか
github_org_name: "toshibe678"

# ランナー名。デフォルトはホスト名
github_runner_name: "{{ ansible_hostname }}"

# 個人ユーザー名かOrganizationオーナーユーザー名
github_account: "toshi-click"
