---
- name: l3 switch setting
  hosts:
    - l3switch
  gather_facts: no
  remote_user: admin
  tasks:
    - name: run multiple commands on remote nodes
      cisco.ios.ios_command:
        commands:
          - show version
          - show interfaces

    - name: enable dhcp server
      cisco.ios.ios_command:
        commands:
          - conf t
          - service dhcp

    - name: setting vlan interface vlan1
      ios_config:
        lines:
          - 'no ip address'
        parents: interface Vlan1

    - name: setting vlan interface vlan99
      ios_config:
        lines:
          - 'ip address 172.28.1.1 255.255.255.0'
          - 'no shutdown'
        parents: interface Vlan99

    - name: setting vlan interface vlan77
      ios_config:
        lines:
          - 'ip address 172.28.77.1 255.255.255.0'
          - 'no shutdown'
        parents: interface Vlan77

    - name: setting vlan interface vlan100
      ios_config:
        lines:
          - 'ip address 172.28.100.1 255.255.255.0'
          - 'no shutdown'
        parents: interface Vlan100

    - name: setting vlan interface vlan177
      ios_config:
        lines:
          - 'ip address 172.28.177.1 255.255.255.0'
          - 'no shutdown'
        parents: interface Vlan177

    - name: setting dhcp
      cisco.ios.ios_command:
        commands:
          - conf t
          - ip dhcp pool DHCP_POOL_VLAN_99
          - network 172.28.1.11 255.255.255.0
          - dns-server 172.16.1.1 172.28.100.53 8.8.8.8
          - default-router 172.28.1.1
          - ip dhcp pool DHCP_POOL_VLAN_77
          - network 172.28.77.0 255.255.255.0
          - dns-server 172.16.1.1 172.28.100.53 8.8.8.8
          - default-router 172.28.77.1
          - ip dhcp pool DHCP_POOL_VLAN_100
          - network 172.28.100.0 255.255.255.0
          - dns-server 172.16.1.1 172.28.100.53 8.8.8.8
          - default-router 172.28.100.1
          - ip dhcp pool DHCP_POOL_VLAN_177
          - network 172.28.177.0 255.255.255.0
          - dns-server 172.16.1.1 172.28.100.53 8.8.8.8
          - default-router 172.28.177.1

    - name: setting router rip
      cisco.ios.ios_command:
        commands:
          - conf t
          - router rip
          - network 172.16.0.0
          - network 172.28.0.0

    - name: Configure interfaces - Status and Descriptions
      ios_interfaces:
        config:
          - name: "{{ item.ios_if }}"
            description: "{{ item.desc }}"
            enabled: "{{ item.enabled }}"
      loop: "{{ interfaces }}"

    - name: Configure interfaces - L3 IPv4
      ios_l3_interfaces:
        config:
          - name: "{{ item.ios_if }}"
            ipv4:
              - address: "{{ item.ipv4 }}"
      when: item.ipv4 is defined
      loop: "{{ interfaces }}"

    - name: Configure interfaces - L3 IPv6
      ios_l3_interfaces:
        config:
          - name: "{{ item.ios_if }}"
            ipv6:
              - address: "{{ item.ipv6 }}"
      when: item.ipv6 is defined
      loop: "{{ interfaces }}"

    - name: Configure interfaces - L3 switchport
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.ios_if }}"
            mode:  "{{ item.mode }}"
            access:
              vlan: "{{ item.vlan_id }}"
        state: merged
      when:
        - item.mode is defined
        - item.mode == "access"
      loop: "{{ interfaces }}"

    - name: Configure interfaces - L3 switchport port fast
      cisco.ios.ios_command:
        commands:
          - conf t
          - "interface {{ item.ios_if }}"
          - spanning-tree portfast
      when:
        - item.mode is defined
        - item.mode == "access"
      loop: "{{ interfaces }}"

    - name: Configure interfaces - L3 trunk
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.ios_if }}"
            mode: "{{ item.mode }}"
            trunk:
              allowed_vlans: "{{ item.allowed_vlans }}"
              native_vlan: "{{ item.native_vlan }}"
              encapsulation: dot1q
        state: merged
      when:
        - item.mode is defined
        - item.mode == "trunk"
      loop: "{{ interfaces }}"

    - name: set DHCP hosts
      cisco.ios.ios_command:
        commands:
          - "clear ip dhcp binding *"
          - conf t
          - "ip dhcp pool {{ item.name }}"
          - "host {{ item.host }} {{ item.subnet }}"
          - "hardware-address {{ item.address }}"
          - "client-identifier {{ item.identifier }}"
      loop: "{{ dhcps }}"
